In [1]:
import pandas as pd
import numpy as np

In [ ]:
date=pd.read_csv('orders.csv')

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
date['date']=pd.to_datetime(date['date'])

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [9]:
#Extracting year,month,days
date['year']=date['date'].dt.year

date

          date  product_id  city_id  orders  year
0   2019-12-10        5628       25       3  2019
1   2018-08-15        3646       14     157  2018
2   2018-10-23        1859       25       1  2018
3   2019-08-17        7292       25       1  2019
4   2019-01-06        4344       25       3  2019
..         ...         ...      ...     ...   ...
995 2018-10-08         255       13       1  2018
996 2018-12-06        5521        7       1  2018
997 2019-05-07         487       26      14  2019
998 2019-03-03        1503       21       2  2019
999 2019-10-15        6371        7      22  2019

[1000 rows x 5 columns]

In [12]:
date['month']=date['date'].dt.month  # for month 
date['month_name']=date['date'].dt.month_name() # for month name

date

          date  product_id  city_id  orders  year  month month_name
0   2019-12-10        5628       25       3  2019     12   December
1   2018-08-15        3646       14     157  2018      8     August
2   2018-10-23        1859       25       1  2018     10    October
3   2019-08-17        7292       25       1  2019      8     August
4   2019-01-06        4344       25       3  2019      1    January
..         ...         ...      ...     ...   ...    ...        ...
995 2018-10-08         255       13       1  2018     10    October
996 2018-12-06        5521        7       1  2018     12   December
997 2019-05-07         487       26      14  2019      5        May
998 2019-03-03        1503       21       2  2019      3      March
999 2019-10-15        6371        7      22  2019     10    October

[1000 rows x 7 columns]

In [22]:
date['day']=date['date'].dt.day
date['dayofweek']=date['date'].dt.dayofweek # for the day of the week
date['dayname']=date['date'].dt.day_name() # for the day of the week name
date['weekofyear']=date['date'].dt.isocalendar().week # week of the year
date['quaterofyear']=date['date'].dt.quarter # quater of the year
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,dayofweek,dayname,is_weekend,weekofyear,quaterofyear
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

In [23]:
# is weekend?

date['is_weekend']=np.where(date['dayname'].isin(['Sunday','Saturday']),1,0)

date

,date,product_id,city_id,orders,year,month,month_name,day,dayofweek,dayname,is_weekend,weekofyear,quaterofyear
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October,8,0,Monday,0,41,4
996,2018-12-06,5521,7,1,2018,12,December,6,3,Thursday,0,49,4
997,2019-05-07,487,26,14,2019,5,May,7,1,Tuesday,0,19,2
998,2019-03-03,1503,21,2,2019,3,March,3,6,Sunday,1,9,1
999,2019-10-15,6371,7,22,2019,10,October,15,1,Tuesday,0,42,4

# Working with time

In [24]:
time=pd.read_csv('messages.csv')
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [26]:
time['date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: date
Non-Null Count  Dtype
--------------  -----
1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [27]:
# its object type so converting to datetime
time['date']=pd.to_datetime(time['date'])

In [28]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [30]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0