In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv("../titanic.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
df.isnull().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [7]:
df

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [8]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [10]:
X_train.isnull().mean()

PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.207865
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.775281
Embarked       0.002809
dtype: float64

In [19]:
X_train['mean_age']=X_train['Age'].fillna(X_train["Age"].mean())
X_train['medain_age']=X_train['Age'].fillna(X_train["Age"].median())

In [15]:
X_test

     PassengerId  Pclass  ... Cabin Embarked
707          708       1  ...   E24        S
37            38       3  ...   NaN        S
615          616       2  ...   NaN        S
169          170       3  ...   NaN        S
68            69       3  ...   NaN        S
..           ...     ...  ...   ...      ...
89            90       3  ...   NaN        S
80            81       3  ...   NaN        S
846          847       3  ...   NaN        S
870          871       3  ...   NaN        S
251          252       3  ...    G6        S

[179 rows x 11 columns]

In [16]:
X_test['mean_age']=X_train['Age'].fillna(X_test["Age"].mean())
X_test['medain_age']=X_train['Age'].fillna(X_test["Age"].median())

In [17]:
X_test

     PassengerId  Pclass  ... mean_age medain_age
707          708       1  ...      NaN        NaN
37            38       3  ...      NaN        NaN
615          616       2  ...      NaN        NaN
169          170       3  ...      NaN        NaN
68            69       3  ...      NaN        NaN
..           ...     ...  ...      ...        ...
89            90       3  ...      NaN        NaN
80            81       3  ...      NaN        NaN
846          847       3  ...      NaN        NaN
870          871       3  ...      NaN        NaN
251          252       3  ...      NaN        NaN

[179 rows x 13 columns]

In [20]:
#To check whether the filling Nan values is good or not we calculate 
# vareince of original dataset and after filling dataset and if the diff 
# in varience is large then it is not preferred


print('Original Age variable variance: ', X_train['Age'].var())
print('Age Variance after median imputation: ', X_train['mean_age'].var())
print('Age Variance after mean imputation: ', X_train['medain_age'].var())

Original Age variable variance:  204.34951339046142
Age Variance after median imputation:  161.81262452718676
Age Variance after mean imputation:  161.98956633460548

Since the diff is huge so mean/medain imputer is not preffered

# Using Sklearn

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [24]:
imp=SimpleImputer(strategy='mean')

X_train['Age']=imp.fit_transform(X_train[['Age']])
X_test['Age']=imp.transform(X_test[['Age']])

In [25]:
X_train

     PassengerId  Pclass  ... Cabin Embarked
30            31       1  ...   NaN        C
10            11       3  ...    G6        S
873          874       3  ...   NaN        S
182          183       3  ...   NaN        S
876          877       3  ...   NaN        S
..           ...     ...  ...   ...      ...
534          535       3  ...   NaN        S
584          585       3  ...   NaN        C
493          494       1  ...   NaN        C
527          528       1  ...   C95        S
168          169       1  ...   NaN        S

[712 rows x 11 columns]