In [90]:
import re 
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [91]:
df=pd.read_csv('IMDB Dataset.csv')

In [92]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [93]:
import textwrap

print(textwrap.fill(df['review'][0], width=80))

One of the other reviewers has mentioned that after watching just 1 Oz episode
you'll be hooked. They are right, as this is exactly what happened with me.<br
/><br />The first thing that struck me about Oz was its brutality and
unflinching scenes of violence, which set in right from the word GO. Trust me,
this is not a show for the faint hearted or timid. This show pulls no punches
with regards to drugs, sex or violence. Its is hardcore, in the classic use of
the word.<br /><br />It is called OZ as that is the nickname given to the Oswald
Maximum Security State Penitentary. It focuses mainly on Emerald City, an
experimental section of the prison where all the cells have glass fronts and
face inwards, so privacy is not high on the agenda. Em City is home to
many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and
more....so scuffles, death stares, dodgy dealings and shady agreements are never
far away.<br /><br />I would say the main appeal of the show is due to the fact
that it goes where other shows wouldn't dare. Forget pretty pictures painted for
mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The
first episode I ever saw struck me as so nasty it was surreal, I couldn't say I
was ready for it, but as I watched more, I developed a taste for Oz, and got
accustomed to the high levels of graphic violence. Not just violence, but
injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill
on order and get away with it, well mannered, middle class inmates being turned
into prison bitches due to their lack of street skills or prison experience)
Watching Oz, you may become comfortable with what is uncomfortable
viewing....thats if you can get in touch with your darker side.

In [94]:
new_df=df.sample(10000)

In [95]:
new_df.shape

(10000, 2)

In [96]:
# Remove HTML tags
def clean_html(text):
    clean=re.compile('<.*?>')
    return re.sub(clean,'',text)

In [97]:
new_df['review']=new_df['review'].apply(clean_html)

In [98]:
new_df['sentiment']=new_df['sentiment'].map({'positive':1,'negative':0})

In [99]:
new_df.head()

                                                  review  sentiment
13470  There have been many film and TV productions o...          1
18748  This is one military drama I like a lot! Tom B...          1
32584  Tempo Di Uccidere (Time To Kill) by Guiliano M...          1
29691  How anyone can praise this crude film version ...          0
34287  The movie was not a waste except for some bori...          0

In [100]:
# converting to lower case
def lower_case(text):
    return text.lower()
new_df['review']=new_df['review'].apply(lower_case)

In [101]:
#funtion to remove special characters

def remove_special(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+' '
            
    return x;
    
new_df['review']=new_df['review'].apply(remove_special)

In [102]:
# Perform Stemming
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [103]:
def stem_words(text):
    return [ps.stem(word) for word in text.split()]

new_df['review']=new_df['review'].apply(stem_words)

In [104]:
# join back

def join_back(list_input):
    return " ".join(list_input)

new_df['review']=new_df['review'].apply(join_back)

In [105]:
new_df.head()

                                                  review  sentiment
13470  there have been mani film and tv product of ja...          1
18748  thi is one militari drama i like a lot tom ber...          1
32584  tempo di uccider time to kill by guiliano mont...          1
29691  how anyon can prais thi crude film version aft...          0
34287  the movi wa not a wast except for some bore sc...          0

In [106]:
X=new_df['review']
y=new_df['sentiment']

In [107]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [108]:
from sklearn.feature_extraction.text import TfidfVectorizer

feature_extraction=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)

In [109]:
X_train_trf = feature_extraction.fit_transform(X_train)
X_test_trf  = feature_extraction.transform(X_test)

In [ ]:
X_train_trf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 717500 stored elements and shape (8000, 32849)>

In [ ]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

# model1=GaussianNB()
model2=MultinomialNB()
model3=BernoulliNB()

In [119]:
# model1.fit(X_train_trf,y_train)
model2.fit(X_train_trf,y_train)
model3.fit(X_train_trf,y_train)

BernoulliNB()

In [123]:
X_train_pred2=model2.predict(X_train_trf)
X_train_pred3=model3.predict(X_train_trf)

In [126]:
print(accuracy_score(X_train_pred2,y_train))
print(accuracy_score(X_train_pred3,y_train))

0.928375
0.918125

In [129]:
y_pred2=model2.predict(X_test_trf)
y_pred3=model3.predict(X_test_trf)

In [130]:
print(accuracy_score(y_test,y_pred2))
print(accuracy_score(y_pred3,y_test))

0.8415
0.825